name: check manpage formatting

on:
  push:
    branches:
    paths:
      - "**.[1-9]"
  pull_request:
    paths:
      - "**.[1-9]"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install mandoc
        run: sudo apt install -y mandoc yq

      - name: lint
        run: |
          dir=$(mktemp -d)
          find subcommands -type f -iname \*.[1-9] -exec cp {} "$dir" \;
          cp plakar.1 plakar-query.7 "$dir"
          cd "$dir"
          mandoc -Tlint -Wstyle -l *
          rm -rf "$dir"

      - name: Ensure man pages are listed in .goreleaser.yml
        run: |
          diff -u <(find ./plakar.1 ./subcommands -name '*.[1-9]' -print0 | xargs -0 -L1 basename | sort) <(cat .goreleaser.yml | yq -r '.nfpms[0].contents[].src' | xargs -L1 basename | sort) || (echo ">> Missing man pages in .gotreleaser.yml for nfpms" && exit 1)
          diff -u <(find ./plakar.1 ./subcommands -name '*.[1-9]' -print0 | xargs -0 -L1 basename | sort) <(cat .goreleaser.yml | yq -r '.homebrew_casks[].manpages[]' | xargs -L1 basename | sort) || (echo ">> Missing man pages in .gotreleaser.yml for homebrew_casks" && exit 1)
